export enum ProvinceValue {
  ANGIANG = 1,
  BARIAVUNGTAU = 2,
  BACLIEU = 3,
  BACGIANG = 4,
  BACKAN = 5,
  BACNINH = 6,
  BENTRE = 7,
  BINHDUONG = 8,
  BINHDINH = 9,
  BINHPHUOC = 10,
  BINHTHUAN = 11,
  CAMAU = 12,
  CAOBANG = 13,
  CANTHO = 14,
  DANANG = 15,
  DAKLAK = 16,
  DAKNONG = 17,
  DIENBIEN = 18,
  DONGNAI = 19,
  DONGTHAP = 20,
  GIALAI = 21,
  HAGIANG = 22,
  HANAM = 23,
  HANOI = 24,
  HATINH = 25,
  HAIDUONG = 26,
  HAIPHONG = 27,
  HAUGIANG = 28,
  HOABINH = 29,
  HUNGYEN = 30,
  KHANHHOA = 31,
  KIENGIANG = 32,
  KONTUM = 33,
  LAICHAU = 34,
  LANGSON = 35,
  LAOCAI = 36,
  LAMDONG = 37,
  LONGAN = 38,
  NAMDINH = 39,
  NGHEAN = 40,
  NINHBINH = 41,
  NINHTHUAN = 42,
  PHUTHO = 43,
  PHUYEN = 44,
  QUANGBINH = 45,
  QUANGNAM = 46,
  QUANGNGAI = 47,
  QUANGNINH = 48,
  QUANGTRI = 49,
  SOCTRANG = 50,
  SONLA = 51,
  TAYNINH = 52,
  THAIBINH = 53,
  THAINGUYEN = 54,
  THANHHOA = 55,
  TPHCM = 56,
  THUATHIENHUE = 57,
  TIENGIANG = 58,
  TRAVINH = 59,
  TUYENQUANG = 60,
  VINHLONG = 61,
  VINHPHUC = 62,
  YENBAI = 63,
}

export enum ProvinceLabel {
  ANGIANG = "An Giang",
  BARIAVUNGTAU = "Bà rịa Vũng Tàu",
  BACLIEU = "Bạc Liêu",
  BACGIANG = "Bắc Giang",
  BACKAN = "Bắc Kạn",
  BACNINH = "Bắc Ninh",
  BENTRE = "Bến Tre",
  BINHDUONG = "Bình Dương",
  BINHDINH = "Bình Định",
  BINHPHUOC = "Bình Phước",
  BINHTHUAN = "Bình Thuận",
  CAMAU = "Cà Mau",
  CAOBANG = "Cao Bằng",
  CANTHO = "Cần Thơ",
  DANANG = "Đà Nẵng",
  DAKLAK = "Đắk Lắk",
  DAKNONG = "Đắk Nông",
  DIENBIEN = "Điện Biên",
  DONGNAI = "Đồng Nai",
  DONGTHAP = "Đồng Tháp",
  GIALAI = "Gia Lai",
  HAGIANG = "Hà Giang",
  HANAM = "Hà Nam",
  HANOI = "Hà Nội",
  HATINH = "Hà Tĩnh",
  HAIDUONG = "Hải Dương",
  HAIPHONG = "Hải Phòng",
  HAUGIANG = "Hậu Giang",
  HOABINH = "Hòa Bình",
  HUNGYEN = "Hưng Yên",
  KHANHHOA = "Khánh Hòa",
  KIENGIANG = "Kiên Giang",
  KONTUM = "Kon Tum",
  LAICHAU = "Lai Châu",
  LANGSON = "Lạng Sơn",
  LAOCAI = "Lào Cai",
  LAMDONG = "Lâm Đồng",
  LONGAN = "Long An",
  NAMDINH = "Nam Định",
  NGHEAN = "Nghệ An",
  NINHBINH = "Ninh Bình",
  NINHTHUAN = "Ninh Thuận",
  PHUTHO = "Phú Thọ",
  PHUYEN = "Phú Yên",
  QUANGBINH = "Quảng Bình",
  QUANGNAM = "Quảng Nam",
  QUANGNGAI = "Quảng Ngãi",
  QUANGNINH = "Quảng Ninh",
  QUANGTRI = "Quảng Trị",
  SOCTRANG = "Sóc Trăng",
  SONLA = "Sơn La",
  TAYNINH = "Tây Ninh",
  THAIBINH = "Thái Bình",
  THAINGUYEN = "Thái Nguyên",
  THANHHOA = "Thanh Hóa",
  THUATHIENHUE = "Thừa Thiên Huế",
  TIENGIANG = "Tiền Giang",
  TPHCM = "TP Hồ Chí Minh",
  TRAVINH = "Trà Vinh",
  TUYENQUANG = "Tuyên Quang",
  VINHLONG = "Vĩnh Long",
  VINHPHUC = "Vĩnh Phúc",
  YENBAI = "Yên Bái",
}
const province = [
  "An Giang",
  "Bà rịa Vũng Tàu",
  "Bạc Liêu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Dương",
  "Bình Định",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cao Bằng",
  "Cần Thơ",
  "Đà Nẵng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Nội",
  "Hà Tĩnh",
  "Hải Dương",
  "Hải Phòng",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lạng Sơn",
  "Lào Cai",
  "Lâm Đồng",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "TP Hồ Chí Minh",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái",
];
export const getProvinceByValue = (value: number) => {
  return province[value - 1];
};
export const getProvinceValue = (label: string) => {
  return province.indexOf(label) + 1;
};
export default {
  province,
  getProvinceByValue,
  getProvinceValue,
};
